tensorboard:
  use: true
  work_dir: runs
  layerwise_logging: true
use_cuda: true
scale_observation: true
version_string: 'mcts'

dimension: 3
max_num_points: 20
max_length_game: 20
max_value: 20
max_grad_norm: 1

eval_batch_size: 10
num_evaluations: 100
eval_on_cpu: true
max_num_considered_actions: 10

discount: 0.99

host:
  batch_size: 256
  optim:
    name: 'adamw'
    args: # Pass optimizer parameters here
      learning_rate: 0.00000001
    # Learning rate scheduling is built-in (by schedule function and `chain`), so we do not specify them.
  #net_arch: [256, 256, 256, 256, 256, 256, 256, 256]
  net_arch: [ 32, 32 ]


agent:
  batch_size: 256
  optim:
    name: 'adamw'
    args: # Pass optimizer parameters here
      learning_rate: 0.00000001
    # Learning rate scheduling is built-in (by schedule function and `chain`), so we do not specify them.
  #net_arch: [256, 256, 256, 256, 256, 256, 256, 256]
  net_arch: [ 32, 32 ]
