use_tensorboard: true
layerwise_logging: true
use_cuda: true
scale_observation: true
version_string: 'mcts'

dimension: 3
max_num_points: 20
max_length_game: 20
max_value: 20
max_grad_norm: 1

eval_batch_size: 10
num_evaluations: 100
max_num_considered_actions: 10
#rollout process repeats `rollout_size//eval_batch_size` amount of times
discount: 0.99

host:
  batch_size: 256
  optim:
    name: 'adamw'
    args: # Pass optimizer parameters here
      learning_rate: 0.00000001
    # Learning rate scheduling is built-in (by schedule function and `chain`), so we do not specify them.
  #net_arch: [256, 256, 256, 256, 256, 256, 256, 256]
  net_arch: [32, 32]


agent:
  batch_size: 256
  optim:
    name: 'adamw'
    args: # Pass optimizer parameters here
      learning_rate: 0.00000001
    # Learning rate scheduling is built-in (by schedule function and `chain`), so we do not specify them.
  #net_arch: [256, 256, 256, 256, 256, 256, 256, 256]
  net_arch: [32, 32]
